language: cpp

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - cmake
            - cmake-data
            - g++-5
            - gcc-5
            - doxygen

before_script:
    - cd documentation
    - if [[ `doxygen Doxyfile 3>&1 1>&2 2>&3 | wc -l` -ne 0 ]]; then exit -1; else echo "Doxygen built with no warnings!"; fi;
    - export CXX="g++-5" COMPILER="g++-5" CC="gcc-5"
    - cd ../test
    - mkdir ./build
    - cd ./build
    - cmake ../
    - make -j

script: ./test_bitter

after_success:
    - cd CMakeFiles/test_bitter.dir/source
    - gcov-5 ./*
    - bash <(curl -s https://codecov.io/bash) -X gcov

