version: '1.0.{build}'

image: Visual Studio 2019

platform:
  - x64
 
configuration:
  - Release
  - Debug

before_build:
    - git submodule init
    - git submodule update
    - cd test
    - mkdir build
    - cd build
    - cmake ../

test_script:
    - $(APPVEYOR_BUILD_FOLDER)\test\build\$(CONFIGURATION)\test_bitter.exe

build:
  project: $(APPVEYOR_BUILD_FOLDER)\test\build\test_bitter.sln